 sudo: required
 dist: trusty

 language: c

# - sudo apt-get install -qq check mpich check bc libattr1-dev python-pip
before_install:
 - test -n $CC  && unset CC
 - test -n $CXX && unset CXX
 - sudo apt-get update -qq
 - sudo apt-cache search openmpi
 - sudo apt-cache search mpich
 - sudo apt-get install -qq check libopenmpi-dev openmpi-bin check bc libattr1-dev python-pip
 - sudo pip install nose

 - set -x
 - OPT="-g -O0"
 - installdir=`pwd`/install
 - mkdir -p deps
 - cd deps

 - libcircle=libcircle-0.2.1-rc.1
 - wget https://github.com/adammoody/libcircle/releases/download/v0.2.1-rc.1/${libcircle}.tar.gz
 - tar -zxf ${libcircle}.tar.gz
 - pushd ${libcircle}
 - ./configure \
        --prefix=${installdir} \
        --disable-silent-rules && \
        make VERBOSE=1 && \
        sudo make VERBOSE=1 install
   #--enable-tests && make && make check && sudo make install
 - popd

 - lwgrp=lwgrp-1.0.2
 - wget https://github.com/hpc/lwgrp/releases/download/v1.0.2/${lwgrp}.tar.gz
 - tar -zxf ${lwgrp}.tar.gz
 - pushd ${lwgrp}
 - ./configure \
        --prefix=${installdir} \
        --disable-silent-rules && \
        make && \
        sudo make install 
   # && make && sudo make install
 - popd

 - dtcmp=dtcmp-1.0.3
 - wget https://github.com/hpc/dtcmp/releases/download/v1.0.3/${dtcmp}.tar.gz
 - tar zxvf ${dtcmp}.tar.gz
 - pushd ${dtcmp}
 - ./configure --prefix=${installdir} --disable-silent-rules --with-lwgrp=${installdir} && make && sudo make install 
   # --with-lwgrp=/usr/local && make && sudo make install
 - popd

 - libarchive=libarchive-3.1.2
 - wget http://www.libarchive.org/downloads/${libarchive}.tar.gz
 - tar zxvf ${libarchive}.tar.gz
 - pushd ${libarchive}
 - export CFLAGS=${OPT}
 - ./configure \
        --prefix=${installdir} && \
        make && \
        sudo make install
   # && make && sudo make install
 - popd

 - cunit=CUnit-2.1-2
 - wget https://sourceforge.net/projects/cunit/files/CUnit/2.1-2/${cunit}-src.tar.bz2 
 - tar xvfj ${cunit}-src.tar.bz2
 - pushd ${cunit}
 - ./configure \
        --prefix=${installdir} && \
        make && \
        sudo make install
   # && make && sudo make install
 - popd

 - sudo ldconfig

 - set -x
 - topdir=`pwd`
 - installdir=$topdir/install
 - export PATH="${topdir}/autotools/install/bin:$PATH"


# script: ./autogen.sh 
script: ./autogen.sh && ./configure && make && make test

 - rm -rf build
 - mkdir -p build
 - cd build

 - export PKG_CONFIG_PATH="${installdir}/lib/pkgconfig"

# TODO: avoid this step
# necessary so configure test of dtcmp links with MPI
 - export CC=mpicc

# hack to get things to build after common library
 - export CFLAGS="-I${topdir}/src/common -DDCOPY_USE_XATTRS"
 - export LDFLAGS="-Wl,-rpath,${topdir}/install/lib -L${topdir}/install/lib -lcircle"

 - ../configure \
        --enable-lustre \
        --prefix=$installdir \
        --disable-silent-rules \
        --with-dtcmp=$installdir && \
        make VERBOSE=1 && \
        make VERBOSE=1 install

compiler:
  - clang
  - gcc

notifications:
  email: false
    #- sikich1@llnl.gov
    #- moody20@llnl.gov
